### ISSUE TITLE
Could not install on 32-bit host.

### ISSUE THREAD

**Issue by smochort11** [piface314/ygo-fabrica#13]
The moment I opened the install.cmd file, there was an error that appeared:
![image](https://user-images.githubusercontent.com/51458751/143935174-b16c5f97-5bca-4537-ae20-7d13bc9bd3fa.png)
This seems to be because of luajit. What can I do, and is this a bug, and if not, how do I install this? This software is definitely 32-bit compatible, so I'm confused.

**Comment by piface314** [comment]
So, as stated in the home page:

> to generate card pics from a card databases, this software uses an image processing library that only works on 64-bit systems. This is irrelevant for the rest of the features, though.

Unfortunately, this is a constraint imposed by one of the dependencies, not by YGOFabrica itself. If you're not interested in the image generation feature (e.g. `ygofab compose` and `ygopic`) though, you can just replace the `luajit` folder for a 32-bit version of LuaJIT, and all the other features should work just fine. Make sure the files inside your new `luajit` folder have the same name as before. You can find information on how to acquire a 32-bit LuaJIT binary for windows [here](http://luajit.org/install.html).
