### ISSUE TITLE
ygofab make not working

### ISSUE THREAD

**Issue by vvakhaze** [piface314/ygo-fabrica#15]
i'm trying to make a Rush Duel version of quintet magician, but for some reason i keep getting this when i try making the expansion

**C:\Users\Vigen>ygofab make quintetmagician
[ERROR] "expansion.quintetmagician" has not been configured
[line break]
[!] It looks like you're not in a project folder...**

I honestly don't know what to do. my project config file is set up like this so maybe that's the problem? I'm unsure though.

**[hash]Use this to define local configurations for your project.
[hash]Any configuration defined here will override its global counterpart.
[hash]Global configurations are located in `C:\Users\Vigen\AppData\Roaming\YGOFabrica\config.toml`.**

**[expansion.quintetmagician]
default = true
recipe = ["vals.toml", "en.toml"]**

**[gamedir.main]
path = '''C:\ProjectIgnis'''**

**[picset.regular]
mode = 'proxy'
size = '512'
artsize = 'cover'
ext = 'png'
year = '????'
author = 'Vigen'
field = true**

I honestly don't know what to do, and I'm seeking help as soon as it's available.

**Comment by piface314** [comment]
As the program stated:
```
[!] It looks like you're not in a project folder...
```

I guess you should change the working directory to your project folder, using the command `cd`, for example, or opnening cmd.exe directly in it.
