### ISSUE TITLE
Name too large

### ISSUE THREAD

**Issue by Denzeduous** [piface314/ygo-fabrica#17]
Hello,

I seem to be having an odd issue when generating my cards. The text is too large and the name of the card goes outside of the box. I checked that the fonts are in the right directory and there are no warnings with that. The rest of the card text is perfectly fine.

Also don't judge this is temp art until I can commission my friend lol.

![210481810](https://user-images.githubusercontent.com/17969338/201247056-fbe234c3-5abe-4ed7-8a8a-648545cc7688.jpg)

**Comment by piface314** [comment]
It definetely looks like a problem with the fonts not being found. Just to be sure, are the fonts inside folder `/res/composer/fonts`? And these are all the files needed:

```
card-name.ttf
edition.ttf
effect.ttf
flavor-text.ttf
init.lua
link-rating.otf
monster-desc.ttf
signature.ttf
values.ttf
```

If you're using Windows, run `dir %LOCALAPPDATA%\YGOFabrica\res\composer\fonts`, or else run `ls ~/.local/ygofab/res/composer/fonts`.

**Comment by Denzeduous** [comment]
Hello piface,

I have every one of those files. Here's the output of my `dir`, and I don't see any inconsistencies unless I'm missing something obvious:
```
11/10/2022  06:00 PM            53,424 card-name.ttf
11/10/2022  06:00 PM            35,728 edition.ttf
11/10/2022  06:00 PM            52,652 effect.ttf
11/10/2022  06:00 PM           105,296 flavor-text.ttf
11/10/2022  05:22 PM               948 init.lua
11/10/2022  06:00 PM            25,972 link-rating.otf
11/10/2022  06:00 PM            61,276 monster-desc.ttf
11/10/2022  05:22 PM               241 README.md
11/10/2022  06:00 PM            65,578 signature.ttf
11/10/2022  06:00 PM            39,524 values.ttf
```
And these are all from `C:\Users\USERNAME\AppData\Local\YGOFabrica\res\composer\fonts`.

**Comment by piface314** [comment]
Okay, try this then. Create two files, one called `test.cmd` with the following content, and place it anywhere:

```cmd
@echo off
setlocal
set "YGOFAB_ROOT=%LOCALAPPDATA%/YGOFabrica"
set "LUA_PATH=%YGOFAB_ROOT%/?.lua;%YGOFAB_ROOT%/?/init.lua;%YGOFAB_ROOT%/modules/share/lua/5.1/?.lua;%YGOFAB_ROOT%/modules/share/lua/5.1/?/init.lua"
set "LUA_CPATH=%YGOFAB_ROOT%/modules/lib/lua/5.1/?.dll"
set "PATH=%YGOFAB_ROOT%/luajit;%YGOFAB_ROOT%/vips/bin;%PATH%"
luajit "%YGOFAB_ROOT%/test.lua" %*
endlocal
@echo on
```

The other called `test.lua`, place it inside YGOFabrica folder, so its full path will be `C:\Users\USERNAME\AppData\Local\YGOFabrica\test.lua`.

```lua
local vips = require 'vips'
local fonts = require 'res.composer.fonts'

local fp = fonts.get_file('card_name')
local fn = fonts.get_family('card_name')
local opt = {font = fn, fontfile = fp, dpi = 300}

local t = vips.Image.text("ComBat Soldier", opt)
t:write_to_file("combat.png")
```

Now run the `test.cmd` file. A new file `combat.png` should appear on the current folder:
![combat](https://user-images.githubusercontent.com/22157025/201921772-f3eadfd6-6fd5-49dd-a47e-b1e19c37134c.png)

**Comment by piface314** [comment]
I had the chance to test YGOFabrica on my friend's laptop, he uses Windows 11, and had the same issue as you, so I guess the solution is the same: [update libvips](https://github.com/libvips/build-win64-mxe/releases/tag/v8.13.2) and it should work. Replace the contents of `YGOFabrica/vips` with the contents of the new version (`vips-dev-w64-all-8.13.2.zip`)

**Comment by piface314** [comment]
Also, as far as I tested, in Windows 11 and using vips most recent versions, the text sometimes gets some extra spaces where it shouldn't. This is not a problem related to YGOFabrica, but I'm leaving this note here in case someone finds this same problem. Let's hope next vips releases fix this issue.

**Comment by Denzeduous** [comment]
Hello piface,

I apologize for the long wait. I have been extremely busy and not able to work on anything recently, and I forgot about this... Updating libvips did indeed fix the issue, thank you! Though, I do have Windows 10 instead of 11, but the fix worked just the same.
