### ISSUE TITLE
Unable to create project

### ISSUE THREAD

**Issue by Yggdrax** [piface314/ygo-fabrica#22]
Whenever I try to create a new project I get a syntax command error.

![Sin título-2](https://user-images.githubusercontent.com/128084074/225716028-8b592c22-82a4-4e4a-98e6-712f66abcefc.png)

Running the latest release v.2.1.0, same issue appears on v2.0.2. There were no issues during installation.

![Sin título-1](https://user-images.githubusercontent.com/128084074/225717325-04926921-cf92-402c-9803-ad21400d7fac.png)

**Comment by piface314** [comment]
As pointed in [the wiki](https://github.com/piface314/ygo-fabrica/wiki/Usage#conventions), you should replace the angle brackets as well to use the commands. E.g.:

```
ygofab new slayerdoll
```
