### ISSUE TITLE
The Effect of the the card is not working

### ISSUE THREAD

**Issue by githubuser98k** [piface314/ygo-fabrica#23]
Sorry for the interruption but sadly when I tested my card, the effect is not working out right, the monster is been activated as spell, fusion spell didn't fusion and the most of the time it just didn't work.
here's the toml in word document and because github won't support toml
[laundry-vals.docx](https://github.com/piface314/ygo-fabrica/files/13763850/laundry-vals.docx)
Here's the zip of the custom card
[custom-regular.zip](https://github.com/piface314/ygo-fabrica/files/13764366/custom-regular.zip)

would you check the file and see am I doing wrong or is it the system's problem.
Thanks

**Comment by piface314** [comment]
Hi there! YGOFabrica does not create the scripts for the cards, it only creates a .lua file with the correct name and boilerplate code for you to edit later. I recommend checking the EDOPro Discord server for information on how to script your custom cards, they have an active community, tools and tutorials that can help you with that.

I checked the files you've attached, and apparently the features that YGOFabrica does support are indeed working, which is the generation of card pictures and the conversion of a text file into a database file.
