### ISSUE TITLE
[Feature Request] Custom Counter support

### ISSUE THREAD

**Issue by monyarm** [piface314/ygo-fabrica#7]
Custom counters have to be added to strings.conf, but cannot be, as ygofab generates strings.conf, but doesn't have support for custom counters.

**Comment by piface314** [comment]
That's a nice idea! I'm kinda out of time to develop lately, so... not sure when this is gonna come out, though :/

**Comment by piface314** [comment]
This feature has been added in 1bea044507520493c29695e58aae118d9de41eb4 and this issue will be closed as soon as v2.0 is released.
