### ISSUE TITLE
v2 fails to install due to incorrect assumption as to locale

### ISSUE THREAD

**Issue by monyarm** [piface314/ygo-fabrica#8]
```
luajit: make.lua:331: ERROR: missing_flag_args --locale
stack traceback:
        [C]: in function 'assert'
        make.lua:331: in main chunk
        [C]: at 0x5559c498c180
```

ygofab uses this to get the locale `locale=$(locale | grep LANGUAGE | cut -d= -f2 | cut -d_ -f1)`
But locale doesn't spit out a line containing LANGUAGE on all distros, on gentoo (or atleast some gentoo installations), locale spits out something like this:

```
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=bg_BG.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT=en_CA.UTF-8
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

changing LANGUAGE to LANG fixes the issue

**Comment by piface314** [comment]
Thanks for warning! (I only saw this today lol) For some reason I'm having trouble with Travis... but this is gonna be included in the next commit :P
